# Generated by Django 4.0.3 on 2022-04-01 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96, verbose_name='Имя категория')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Место на карте')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Место на карте',
                'verbose_name_plural': 'Места на карте',
            },
        ),
        migrations.CreateModel(
            name='MapCsGo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96, verbose_name='Карта')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название раскидки')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение карты')),
                ('video', models.FileField(upload_to='', verbose_name='Видео')),
                ('category', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('map', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='mainapp.mapcsgo', verbose_name='Карта')),
                ('place_on_map', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.place', verbose_name='Место на карте')),
            ],
            options={
                'verbose_name': 'Раскидка',
                'verbose_name_plural': 'Раскидки',
            },
        ),
    ]
