# Generated by Django 3.2.8 on 2022-04-01 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='mapcsgo',
            options={'verbose_name': 'Карта', 'verbose_name_plural': 'Карты'},
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название раскидки')),
                ('video', models.FileField(upload_to='', verbose_name='Видео')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('map', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='mainapp.mapcsgo', verbose_name='Карта')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
            },
        ),
    ]
