# Generated by Django 4.0.3 on 2022-04-03 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_mapcsgo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='place_on_map',
            field=models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='mainapp.place', verbose_name='Место на карте'),
        ),
    ]
