# Generated by Django 3.2.8 on 2022-04-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20220401_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Раскидка', 'verbose_name_plural': 'Раскидки'},
        ),
        migrations.RemoveField(
            model_name='mapcsgo',
            name='category',
        ),
        migrations.AddField(
            model_name='content',
            name='place',
            field=models.CharField(blank=True, choices=[('MID', 'MIDDLE'), ('A', 'A'), ('B', 'B')], max_length=3, null=True),
        ),
    ]
